# -*- coding: utf-8 -*-
"""Project2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OzhYrGfJdjCFhqX5XPXLENkDAtr8reCH

DATA 611 - Predictive Analysis (L01)

Winter 2026

Project 2

# Cross-Asset and Sector-Wide Analysis to Predict Suncor Returns

Group 3

Group Members: Bhuvan Dubey and Andrea Abenoja

# Import libraries
"""

import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import mean_squared_error, roc_curve, roc_auc_score
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

# Originally developed in Google Colab (with Google Drive mounted for data access).
# For portability, load the dataset from a local relative path instead:
file_path = os.path.join("..", "data", "Project2Dataset_final.csv")
print(file_path)

# Load data
daily_returns_df = pd.read_csv(file_path)
daily_returns_df.head()

# Convert 'Date' to datetime
daily_returns_df['Date'] = pd.to_datetime(daily_returns_df['Date'])

# Define features and target
features = [
    'USOF_daily_return', 'USDtoCAD_daily_return',
    'shell_daily_return', 'imperial_oil_daily_return',
    'cenovus_daily_return', 'cnrl_daily_return'
]
target = 'suncor_daily_return'

X = daily_returns_df[features]
y = daily_returns_df[target]

X = X.copy()
y = y.copy()

# Handle missing/infinite values
X.replace([np.inf, -np.inf], np.nan, inplace=True)
y.replace([np.inf, -np.inf], np.nan, inplace=True)

# Drop rows with NaN values
X.dropna(inplace=True)
y = y.loc[X.index]

# Split data into train and test sets
split_index = int(len(X) * 0.7)
X_train, X_test = X.iloc[:split_index], X.iloc[split_index:]
y_train, y_test = y.iloc[:split_index], y.iloc[split_index:]

"""Multiple Linear Regression"""

mlr = LinearRegression()
mlr.fit(X_train, y_train)
y_pred_mlr = mlr.predict(X_test)

from sklearn.metrics import r2_score
import statsmodels.api as sm

# R2 from test set
r2_test = r2_score(y_test, y_pred_mlr)
n = len(y_test)
k = X_test.shape[1]
adj_r2 = 1 - (1 - r2_test) * (n - 1) / (n - k - 1)
print(f"Adjusted R2 from test set: {adj_r2:.4f}")

# Compare RMSE to baseline (predicting the mean)
baseline_rmse = np.sqrt(mean_squared_error(y_test, np.full_like(y_test, y_train.mean())))
rmse_mlr = np.sqrt(mean_squared_error(y_test, y_pred_mlr))
print(f"Baseline RMSE (mean predictor): {baseline_rmse:.6f}")
print(f"RMSE reduction over baseline: {(1 - rmse_mlr/baseline_rmse)*100:.2f}%")

# Get p-values and adjusted R2 of training set via statsmodels
X_train_sm = sm.add_constant(X_train)
ols_model = sm.OLS(y_train, X_train_sm).fit()
print(ols_model.summary())

# VIF to check multicollinearity
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif_data = pd.DataFrame()
vif_data['feature'] = X.columns
vif_data['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
print(vif_data)

"""VIF interpretation:

VIF = 1 no correlation

VIF 1-5 = moderate correlation, acceptable
"""

import matplotlib.dates as mdates

# Get Dates for x axis
test_set_dates = daily_returns_df.loc[y_test.index,'Date']

# Plot actual vs predicted
fig, ax = plt.subplots(figsize=(12,6))
ax.plot(test_set_dates, y_test.values, label='Actual')
ax.plot(test_set_dates, y_pred_mlr, label='Predicted')
ax.set_title('MLR: Actual vs Predicted Suncor Returns')
ax.set_ylabel('Daily Return')
ax.set_xlabel('Dates from Test Set')
ax.legend()

# Make major ticks the year on x axis
ax.xaxis.set_major_locator(mdates.YearLocator())
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))

#Make minor ticks the month on x axiis
ax.xaxis.set_minor_locator(mdates.MonthLocator())
ax.xaxis.set_minor_formatter(mdates.DateFormatter('%b'))

# Format x axis
ax.tick_params(axis='x', which='major', labelsize=9, pad=15, rotation=45)
ax.tick_params(axis='x', which='minor', labelsize=7)

plt.tight_layout()
plt.show()

residuals = y_test - y_pred_mlr

# Check for Assumptions - Normality of Residuals (QQ plot)
plt.figure(figsize=(6,6))
stats.probplot(residuals, dist="norm", plot=plt)
plt.title('QQ Plot of Residuals')
plt.show()

# Check for Assumptions - Heteroskedasticity

fig, ax = plt.subplots(figsize=(6,6))
ax.scatter(y_pred_mlr, residuals)
ax.axhline(y=0, color='r', linestyle='--')
ax.set_xlabel('Predicted Values')
ax.set_ylabel('Residuals')
ax.set_title('Residuals vs Predicted Values')
plt.show()

# Check for Assumptions - Multicollinearity

# Correlation Matrix
corr_matrix = X_train.corr()

fig, ax = plt.subplots(figsize=(10,8))
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', ax=ax)
ax.set_title('Correlation Matrix')
plt.tight_layout()
plt.show()

# Check for Assumption - Influential Points (Cook's Distance)
import statsmodels.api as sm

model = sm.OLS(y_train, sm.add_constant(X_train)).fit()

influence = model.get_influence()
cooks_distance = influence.cooks_distance[0]

fig, ax = plt.subplots(figsize=(6,6))
ax.scatter(range(len(cooks_distance)), cooks_distance, s=5, color = 'black')
ax.axhline(y=4/len(X_train), color='r', linestyle='--')
ax.set_xlabel('Observation')
ax.set_ylabel('Cook\'s Distance')
ax.set_title('Cook\'s Distance Plot')
plt.show()

"""Random Forest Regression"""

rf = RandomForestRegressor(
    n_estimators=100,
    max_features='sqrt',
    min_samples_leaf=5,
    random_state=42
)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

# RMSE
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
print(f"Random Forest RMSE: {rmse_rf:.6f}")

import matplotlib.dates as mdates

# Get Dates for x axis
test_set_dates = daily_returns_df.loc[y_test.index, 'Date']

# Plot actual vs predicted
plt.figure(figsize=(12,6))
plt.plot(test_set_dates, y_test.values, label='Actual')
plt.plot(test_set_dates, y_pred_rf, label='Predicted')
plt.title('Random Forest: Actual vs Predicted Suncor Returns')
plt.xlabel('Dates from Test Set')
plt.ylabel('Return')
plt.legend()

# Get current axes
ax = plt.gca()

# Set major ticks as years
ax.xaxis.set_major_locator(mdates.YearLocator())
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))

# Set minor ticks as months
ax.xaxis.set_minor_locator(mdates.MonthLocator())
ax.xaxis.set_minor_formatter(mdates.DateFormatter('%b'))

# Rotate major tick labels for clarity
ax.tick_params(axis='x', which='major', labelsize=9, pad=15, rotation=45)
ax.tick_params(axis='x', which='minor', labelsize=7)

plt.tight_layout()
plt.show()

# Feature importance
importances = rf.feature_importances_
indices = np.argsort(importances)

plt.figure(figsize=(8,6))
plt.barh(range(len(indices)), importances[indices], align='center')
plt.yticks(range(len(indices)), [features[i] for i in indices])
plt.title('Feature Importance in Random Forest')
plt.xlabel('Importance')
plt.ylabel('Features')
plt.show()

# Get feature importances
importances = rf.feature_importances_

# Get feature names
feature_names = X_train.columns

# Create a sorted list of features by importance
sorted_indices = np.argsort(importances)[::-1]
sorted_features = [feature_names[i] for i in sorted_indices]
sorted_importances = importances[sorted_indices]

# Print
for feature, importance in zip(sorted_features, sorted_importances):
    print(f"{feature}: {importance:.4f}")

# Classification Analysis
# Define split index again for classification
split_idx = int(len(X) * 0.7)

# Create binary target (1 if return > 0 else 0)
y_class = (y > 0).astype(int)

X_class = X.copy()
X_class = X_class.loc[y_class.index]

# Split for classification
X_train_c, X_test_c = X_class.iloc[:split_idx], X_class.iloc[split_idx:]
y_train_c, y_test_c = y_class.iloc[:split_idx], y_class.iloc[split_idx:]

# Random Forest Classifier
rf_clf = RandomForestClassifier(
    n_estimators=100,
    max_features='sqrt',
    min_samples_leaf=5,
    random_state=42
)
rf_clf.fit(X_train_c, y_train_c)

# Predict probabilities for ROC
y_scores = rf_clf.predict_proba(X_test_c)[:, 1]

# ROC curve and AUC
fpr, tpr, thresholds = roc_curve(y_test_c, y_scores)
roc_auc = roc_auc_score(y_test_c, y_scores)
print(f"ROC AUC: {roc_auc:.3f}")

# Plot ROC curve
plt.figure(figsize=(8,6))
plt.plot(fpr, tpr, label=f'ROC curve (area = {roc_auc:.2f})')
plt.plot([0,1], [0,1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for Suncor Return Direction Prediction')
plt.legend(loc='lower right')
plt.show()

from sklearn.inspection import PartialDependenceDisplay

# Select top N features based on importance
top_n = 5
top_features_indices = np.argsort(importances)[-top_n:]
top_features = [features[i] for i in top_features_indices]

# Plot partial dependence for top features
fig, ax = plt.subplots(figsize=(15, 10))
PartialDependenceDisplay.from_estimator(
    rf, X_train, features=top_features, ax=ax
)
plt.suptitle('Partial Dependence Plots for Top Features')
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()